services:
  fhem:
    image: ghcr.io/fhem/fhem-docker:5-bookworm
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./fhem/:/opt/fhem/
    environment:
      TZ: Europe/Berlin

  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    profiles:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fhem}
      POSTGRES_USER: ${POSTGRES_USER:-fhem}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fhem}
      TZ: ${TZ:-Europe/Berlin}

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    profiles:
      - mail
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
